### PR TITLE
s582: admin improvements part 2

### PR DESCRIPTION
**Pull request by ProtoJazz**
Added new lables to requests, moved some strings into resx files

### CODE REVIEW

**Comment by tidusjar** [comment]
Nice!

Let me know when you have made all the changes for me to merge it in :)

**Comment by ProtoJazz** [comment]
Tried replying by email. Dont think it worked 

I think for this unit of work this is pretty much it,  unless you see something missing. I'm trying to keep my PRs small because I'm not sure when I'll get time to work on stuff. And it's a pain to merge a big change if it's been sitting for a while.

**Comment by tidusjar** [comment]
OK cool :) Thanks!

**Comment by ProtoJazz** [comment]
I think for this unit of work this is pretty much it,  unless you see
something missing. I'm trying to keep my PRs small because I'm not sure
when I'll get time to work on stuff. And it's a pain to merge a big change
if it's been sitting for a while.

**Pull request merged**
