### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by liveyourheart**
* Created properties to allow admin to disable tv requests by episode or specific season
* WIP of actually hiding/showing request options based on settings

### CODE REVIEW

**Comment by liveyourheart** [comment]
* finished wiring the settings into the the TV search UI.

**Comment by tidusjar** [comment]
Thanks a lot! Is that all the changes you plan to make in this PR? Looks good!

**Comment by liveyourheart** [comment]
I don't have any other changes in mind unless you have some suggestions.

**Comment by tidusjar** [comment]
Thanks!

**Pull request merged**
