### PR TITLE
Update DateTimeHelper.cs

### PR DESCRIPTION
**Pull request by richardpoyner**
I got an 500 error on my NAS.
This fixed that error.

### CODE REVIEW

**Comment by tidusjar** [comment]
The issue with this is that there was a reason why the top bit was commented out, I can't remember off the top of my head but there were issues with it running on mono...

What was the error/exception you were having?

**Comment by richardpoyner** [comment]
I do not know if i am going crazy or something. But just got lastest and ran the same code. And for some reason now, it works. So sorry to bother you.
I will close this.

**Comment by tidusjar** [comment]
Haha that's fine!

**Comment by richardpoyner** [comment]
Tried to start over with new install and got the error again:

server:3579/requests/movies

------

Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object
  at PlexRequests.Helpers.DateTimeHelper.OffsetUTCDateTime (System.DateTime utcDateTime, System.Int32 minuteOffset) [0x00006] in <142f17213a7047a996d14b3058bbe6f4>:0 
  at PlexRequests.UI.Modules.RequestsModule+<>c__DisplayClass42_1.b__5 (PlexRequests.Store.RequestedModel movie) [0x000a2] in :0 
  at System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () [0x00064] in <5f01f5aacbb346938d6f9b4e69d4383a>:0 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x0008b] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in <5f01f5aacbb346938d6f9b4e69d4383a>:0 
  at PlexRequests.UI.Modules.RequestsModule+d__42.MoveNext () [0x0029b] in :0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at PlexRequests.UI.Modules.RequestsModule+<<-ctor>b__0_1>d.MoveNext () [0x00060] in :0 
   --- End of inner exception stack trace ---
  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) [0x000bd] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

**Comment by SuperPotatoMen** [comment]
Can you open a issue for this one instead of a PR?, i'm sure we not going to merge this one.

**Pull request closed without merging**
